# Generated by Django 2.2.7 on 2019-12-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191217_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='yil',
            field=models.CharField(default=False, max_length=50, verbose_name='Year'),
        ),
    ]
