# Generated by Django 2.2.7 on 2019-12-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_yil'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.CharField(default=False, max_length=50, verbose_name='Imdb'),
        ),
        migrations.AddField(
            model_name='movie',
            name='turu',
            field=models.CharField(default=False, max_length=100, verbose_name='Sort'),
        ),
    ]
