# Generated by Django 2.2.7 on 2019-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191221_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='turu',
            field=models.CharField(default='', max_length=100, verbose_name='Category'),
        ),
    ]
